/* This file is generated by scripts/generate-content.ts. Edit content/cards/*.yaml instead. */
import type { CardTemplate } from "./types";

export const CARD_TEMPLATES: CardTemplate[] = [
  {
    "id": "piasa-whelp",
    "name": "Piasa Whelp",
    "collectorNumber": "CORE-001",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 1,
      "right": 5,
      "bottom": 1,
      "left": 4
    },
    "lore": "A courier sworn to carry living coals between border keeps.",
    "palette": {
      "primary": "#b64b39",
      "secondary": "#f4b66b",
      "ink": "#261915"
    },
    "series": "core",
    "artUrl": "/cards/core/piasa-whelp.png"
  },
  {
    "id": "dire-wolf",
    "name": "Dire Wolf",
    "collectorNumber": "CORE-002",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 3,
      "right": 1,
      "bottom": 5,
      "left": 1
    },
    "lore": "Her mirror-water shows only choices already half made.",
    "palette": {
      "primary": "#297b73",
      "secondary": "#83c7bb",
      "ink": "#10201f"
    },
    "series": "core",
    "artUrl": "/cards/core/dire-wolf.png"
  },
  {
    "id": "wooly-rhino",
    "name": "Wooly Rhino",
    "collectorNumber": "CORE-003",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 6,
      "right": 1,
      "bottom": 1,
      "left": 2
    },
    "lore": "A patient guard whose oath is carved deeper than steel.",
    "palette": {
      "primary": "#66717a",
      "secondary": "#d1c5ad",
      "ink": "#171a1c"
    },
    "series": "core",
    "artUrl": "/cards/core/wooly-rhino.png"
  },
  {
    "id": "homonculus",
    "name": "Homonculus",
    "collectorNumber": "CORE-004",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Construct",
    "sides": {
      "top": 1,
      "right": 3,
      "bottom": 3,
      "left": 5
    },
    "lore": "Every verse leaves a green hook in the listener's heart.",
    "palette": {
      "primary": "#557a3b",
      "secondary": "#c9d88f",
      "ink": "#172112"
    },
    "series": "core",
    "artUrl": "/cards/core/homonculus.png"
  },
  {
    "id": "adze",
    "name": "Adze",
    "collectorNumber": "CORE-005",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 2,
      "right": 6,
      "bottom": 1,
      "left": 1
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/adze.png"
  },
  {
    "id": "elephant-bird",
    "name": "Elephant Bird",
    "collectorNumber": "CORE-006",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 1,
      "right": 5,
      "bottom": 4,
      "left": 1
    },
    "lore": "He taxes smoke, ash, and every spark that escapes a hearth.",
    "palette": {
      "primary": "#87362e",
      "secondary": "#d99450",
      "ink": "#211211"
    },
    "series": "core",
    "artUrl": "/cards/core/elephant-bird.png"
  },
  {
    "id": "areneid",
    "name": "Areneid",
    "collectorNumber": "CORE-007",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 2,
      "right": 1,
      "bottom": 4,
      "left": 4
    },
    "lore": "She descends with empty hands and returns carrying lost names.",
    "palette": {
      "primary": "#315c95",
      "secondary": "#bad7ff",
      "ink": "#111a2b"
    },
    "series": "core",
    "artUrl": "/cards/core/areneid.png"
  },
  {
    "id": "rotted-zombie",
    "name": "Rotted Zombie",
    "collectorNumber": "CORE-008",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Undead",
    "sides": {
      "top": 4,
      "right": 2,
      "bottom": 4,
      "left": 3
    },
    "lore": "A forest sovereign that remembers the first road.",
    "palette": {
      "primary": "#49642e",
      "secondary": "#d7c16f",
      "ink": "#161c12"
    },
    "series": "core",
    "artUrl": "/cards/core/rotted-zombie.png"
  },
  {
    "id": "brittle-skeleton",
    "name": "Brittle Skeleton",
    "collectorNumber": "CORE-009",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Undead",
    "sides": {
      "top": 2,
      "right": 1,
      "bottom": 2,
      "left": 6
    },
    "lore": "He maps the invisible roads between vows, storms, and stars.",
    "palette": {
      "primary": "#4f5d8f",
      "secondary": "#d9c6ff",
      "ink": "#181827"
    },
    "series": "core",
    "artUrl": "/cards/core/brittle-skeleton.png"
  },
  {
    "id": "squonk",
    "name": "Squonk",
    "collectorNumber": "CORE-010",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Eldritch",
    "sides": {
      "top": 3,
      "right": 5,
      "bottom": 2,
      "left": 1
    },
    "lore": "A ruler whose shadow moves half a breath before the body.",
    "palette": {
      "primary": "#29223d",
      "secondary": "#bfa3ff",
      "ink": "#0d0a14"
    },
    "series": "core",
    "artUrl": "/cards/core/squonk.png"
  },
  {
    "id": "relic-hunter",
    "name": "Relic Hunter",
    "collectorNumber": "CORE-011",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Human",
    "sides": {
      "top": 2,
      "right": 3,
      "bottom": 1,
      "left": 5
    },
    "lore": "A ruler whose shadow moves half a breath before the body.",
    "palette": {
      "primary": "#29223d",
      "secondary": "#bfa3ff",
      "ink": "#0d0a14"
    },
    "series": "core",
    "artUrl": "/cards/core/relic-hunter.png"
  },
  {
    "id": "plague-rat",
    "name": "Plague Rat",
    "collectorNumber": "CORE-011",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 4,
      "right": 2,
      "bottom": 4,
      "left": 2
    },
    "lore": "A ruler whose shadow moves half a breath before the body.",
    "palette": {
      "primary": "#29223d",
      "secondary": "#bfa3ff",
      "ink": "#0d0a14"
    },
    "series": "core",
    "artUrl": "/cards/core/plague-rat.png"
  },
  {
    "id": "cutthroat",
    "name": "Cutthroat",
    "collectorNumber": "CORE-011",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Human",
    "sides": {
      "top": 1,
      "right": 3,
      "bottom": 4,
      "left": 3
    },
    "lore": "A ruler whose shadow moves half a breath before the body.",
    "palette": {
      "primary": "#29223d",
      "secondary": "#bfa3ff",
      "ink": "#0d0a14"
    },
    "series": "core",
    "artUrl": "/cards/core/cutthroat.png"
  },
  {
    "id": "natari-erudite",
    "name": "Natari Erudite",
    "collectorNumber": "CORE-011",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Kynathi",
    "sides": {
      "top": 4,
      "right": 5,
      "bottom": 1,
      "left": 1
    },
    "lore": "A ruler whose shadow moves half a breath before the body.",
    "palette": {
      "primary": "#29223d",
      "secondary": "#bfa3ff",
      "ink": "#0d0a14"
    },
    "series": "core",
    "artUrl": "/cards/core/natari-erudite.png"
  },
  {
    "id": "ghuler",
    "name": "Ghuler",
    "collectorNumber": "CORE-012",
    "rarity": "UNCOMMON",
    "tier": 1,
    "affinity": "Eldritch",
    "sides": {
      "top": 1,
      "right": 1,
      "bottom": 5,
      "left": 5
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/ghuler.png"
  },
  {
    "id": "sparmos-blacksmith",
    "name": "Sparmos Blacksmith",
    "collectorNumber": "CORE-013",
    "rarity": "RARE",
    "tier": 1,
    "affinity": "Human",
    "sides": {
      "top": 3,
      "right": 6,
      "bottom": 1,
      "left": 3
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/sparmos-blacksmith.png"
  },
  {
    "id": "roc",
    "name": "Roc",
    "collectorNumber": "CORE-014",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Beast",
    "sides": {
      "top": 6,
      "right": 2,
      "bottom": 2,
      "left": 3
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/roc.png"
  },
  {
    "id": "forest-troll",
    "name": "Forest Troll",
    "collectorNumber": "CORE-015",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Beast",
    "sides": {
      "top": 5,
      "right": 3,
      "bottom": 3,
      "left": 4
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/forest-troll.png"
  },
  {
    "id": "moonwell-diver",
    "name": "Moonwell Diver",
    "collectorNumber": "CORE-016",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Alnathi",
    "sides": {
      "top": 4,
      "right": 1,
      "bottom": 6,
      "left": 3
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/moonwell-diver.png"
  },
  {
    "id": "kynathi-highborn",
    "name": "Kynathi Highborn",
    "collectorNumber": "CORE-017",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Kynathi",
    "sides": {
      "top": 3,
      "right": 4,
      "bottom": 5,
      "left": 3
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/kynathi-highborn.png"
  },
  {
    "id": "ghoul",
    "name": "Ghoul",
    "collectorNumber": "CORE-018",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Undead",
    "sides": {
      "top": 5,
      "right": 3,
      "bottom": 2,
      "left": 5
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/ghoul.png"
  },
  {
    "id": "red-imp",
    "name": "Red Imp",
    "collectorNumber": "CORE-018",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Eldritch",
    "sides": {
      "top": 1,
      "right": 5,
      "bottom": 3,
      "left": 5
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/red-imp.png"
  },
  {
    "id": "blue-imp",
    "name": "Blue Imp",
    "collectorNumber": "CORE-018",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Eldritch",
    "sides": {
      "top": 5,
      "right": 2,
      "bottom": 5,
      "left": 2
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/blue-imp.png"
  },
  {
    "id": "skraal",
    "name": "Skraal",
    "collectorNumber": "CORE-018",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Aberration",
    "sides": {
      "top": 4,
      "right": 4,
      "bottom": 5,
      "left": 2
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/skraal.png"
  },
  {
    "id": "broken-doll",
    "name": "Broken Doll",
    "collectorNumber": "CORE-018",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Construct",
    "sides": {
      "top": 5,
      "right": 2,
      "bottom": 5,
      "left": 3
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/broken-doll.png"
  },
  {
    "id": "siguapa",
    "name": "Siguapa",
    "collectorNumber": "CORE-019",
    "rarity": "UNCOMMON",
    "tier": 3,
    "affinity": "Eldritch",
    "sides": {
      "top": 5,
      "right": 5,
      "bottom": 3,
      "left": 5
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/siguapa.png"
  },
  {
    "id": "snallygaster",
    "name": "Snallygaster",
    "collectorNumber": "CORE-020",
    "rarity": "UNCOMMON",
    "tier": 4,
    "affinity": "Eldritch",
    "sides": {
      "top": 4,
      "right": 6,
      "bottom": 6,
      "left": 3
    },
    "lore": "Its wings ring like bells before a clean strike.",
    "palette": {
      "primary": "#4f8fa8",
      "secondary": "#d7f0f4",
      "ink": "#10242b"
    },
    "series": "core",
    "artUrl": "/cards/core/snallygaster.png"
  }
];
