/* This file is generated by scripts/generate-content.ts. Edit content/cards/*.yaml instead. */
import type { CardTemplate } from "./types";

export const CARD_TEMPLATES: CardTemplate[] = [
  {
    "id": "piasa-whelp",
    "name": "Piasa Whelp",
    "collectorNumber": "CORE-001",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 1,
      "right": 5,
      "bottom": 1,
      "left": 4
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#b64b39",
      "secondary": "#f4b66b",
      "ink": "#261915"
    },
    "series": "core",
    "artUrl": "/cards/core/piasa-whelp.png"
  },
  {
    "id": "dire-wolf",
    "name": "Dire Wolf",
    "collectorNumber": "CORE-002",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 3,
      "right": 1,
      "bottom": 5,
      "left": 1
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#3f4f55",
      "secondary": "#b8c7c9",
      "ink": "#11181a"
    },
    "series": "core",
    "artUrl": "/cards/core/dire-wolf.png"
  },
  {
    "id": "wooly-rhino",
    "name": "Wooly Rhino",
    "collectorNumber": "CORE-003",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 6,
      "right": 1,
      "bottom": 1,
      "left": 2
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#66717a",
      "secondary": "#d1c5ad",
      "ink": "#171a1c"
    },
    "series": "core",
    "artUrl": "/cards/core/wooly-rhino.png"
  },
  {
    "id": "homonculus",
    "name": "Homunculus",
    "collectorNumber": "CORE-004",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Construct",
    "sides": {
      "top": 1,
      "right": 3,
      "bottom": 3,
      "left": 5
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#5f6f78",
      "secondary": "#c7d2d8",
      "ink": "#151b1f"
    },
    "series": "core",
    "artUrl": "/cards/core/homonculus.png"
  },
  {
    "id": "adze",
    "name": "Adze",
    "collectorNumber": "CORE-005",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 2,
      "right": 6,
      "bottom": 1,
      "left": 1
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#7f3f45",
      "secondary": "#f0a05d",
      "ink": "#211113"
    },
    "series": "core",
    "artUrl": "/cards/core/adze.png"
  },
  {
    "id": "elephant-bird",
    "name": "Elephant Bird",
    "collectorNumber": "CORE-006",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 1,
      "right": 5,
      "bottom": 4,
      "left": 1
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#87362e",
      "secondary": "#d99450",
      "ink": "#211211"
    },
    "series": "core",
    "artUrl": "/cards/core/elephant-bird.png"
  },
  {
    "id": "areneid",
    "name": "Areneid",
    "collectorNumber": "CORE-007",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Beast",
    "sides": {
      "top": 2,
      "right": 1,
      "bottom": 4,
      "left": 4
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#315c95",
      "secondary": "#bad7ff",
      "ink": "#111a2b"
    },
    "series": "core",
    "artUrl": "/cards/core/areneid.png"
  },
  {
    "id": "rotted-zombie",
    "name": "Rotted Zombie",
    "collectorNumber": "CORE-008",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Undead",
    "sides": {
      "top": 4,
      "right": 2,
      "bottom": 4,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#49642e",
      "secondary": "#d7c16f",
      "ink": "#161c12"
    },
    "series": "core",
    "artUrl": "/cards/core/rotted-zombie.png"
  },
  {
    "id": "brittle-skeleton",
    "name": "Brittle Skeleton",
    "collectorNumber": "CORE-009",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Undead",
    "sides": {
      "top": 2,
      "right": 1,
      "bottom": 2,
      "left": 6
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#6f6658",
      "secondary": "#e2d3ac",
      "ink": "#1d1a16"
    },
    "series": "core",
    "artUrl": "/cards/core/brittle-skeleton.png"
  },
  {
    "id": "squonk",
    "name": "Squonk",
    "collectorNumber": "CORE-010",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Aberration",
    "sides": {
      "top": 3,
      "right": 5,
      "bottom": 2,
      "left": 1
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#4d3358",
      "secondary": "#d8a7cf",
      "ink": "#160f19"
    },
    "series": "core",
    "artUrl": "/cards/core/squonk.png"
  },
  {
    "id": "relic-hunter",
    "name": "Relic Hunter",
    "collectorNumber": "CORE-011",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Human",
    "sides": {
      "top": 2,
      "right": 3,
      "bottom": 1,
      "left": 5
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#6b5232",
      "secondary": "#d9bd75",
      "ink": "#1f170e"
    },
    "series": "core",
    "artUrl": "/cards/core/relic-hunter.png"
  },
  {
    "id": "plague-rat",
    "name": "Plague Rat",
    "collectorNumber": "CORE-012",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Aberration",
    "sides": {
      "top": 4,
      "right": 2,
      "bottom": 4,
      "left": 2
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#3d5b3a",
      "secondary": "#bccb6b",
      "ink": "#111a10"
    },
    "series": "core",
    "artUrl": "/cards/core/plague-rat.png"
  },
  {
    "id": "cutthroat",
    "name": "Cutthroat",
    "collectorNumber": "CORE-013",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Human",
    "sides": {
      "top": 1,
      "right": 3,
      "bottom": 4,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#5a2e36",
      "secondary": "#d1836f",
      "ink": "#1c0f12"
    },
    "series": "core",
    "artUrl": "/cards/core/cutthroat.png"
  },
  {
    "id": "natari-erudite",
    "name": "Natari Erudite",
    "collectorNumber": "CORE-014",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Kynathi",
    "sides": {
      "top": 4,
      "right": 5,
      "bottom": 1,
      "left": 1
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#40325f",
      "secondary": "#c8b6ff",
      "ink": "#151020"
    },
    "series": "core",
    "artUrl": "/cards/core/natari-erudite.png"
  },
  {
    "id": "tipsy-wyvern-wench",
    "name": "Tipsy Wyvern Wench",
    "collectorNumber": "CORE-014",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Human",
    "sides": {
      "top": 1,
      "right": 5,
      "bottom": 3,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#40325f",
      "secondary": "#c8b6ff",
      "ink": "#151020"
    },
    "series": "core",
    "artUrl": "/cards/core/tipsy-wyvern-wench.png"
  },
  {
    "id": "reshai-maskrunner",
    "name": "Reshai Maskrunner",
    "collectorNumber": "CORE-014",
    "rarity": "COMMON",
    "tier": 1,
    "affinity": "Reshai",
    "sides": {
      "top": 2,
      "right": 5,
      "bottom": 1,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#40325f",
      "secondary": "#c8b6ff",
      "ink": "#151020"
    },
    "series": "core",
    "artUrl": "/cards/core/reshai-maskrunner.png"
  },
  {
    "id": "ghuler",
    "name": "Ghuler",
    "collectorNumber": "CORE-015",
    "rarity": "UNCOMMON",
    "tier": 1,
    "affinity": "Eldritch",
    "sides": {
      "top": 1,
      "right": 1,
      "bottom": 5,
      "left": 5
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#2a284a",
      "secondary": "#c08cff",
      "ink": "#0d0b18"
    },
    "series": "core",
    "artUrl": "/cards/core/ghuler.png"
  },
  {
    "id": "sparmos-blacksmith",
    "name": "Sparmos Blacksmith",
    "collectorNumber": "CORE-016",
    "rarity": "RARE",
    "tier": 1,
    "affinity": "Human",
    "sides": {
      "top": 3,
      "right": 6,
      "bottom": 1,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#6d3c2f",
      "secondary": "#e0a35a",
      "ink": "#1f120d"
    },
    "series": "core",
    "artUrl": "/cards/core/sparmos-blacksmith.png"
  },
  {
    "id": "velvet-thorn-courtesan",
    "name": "Velvet Thorn Courtesan",
    "collectorNumber": "CORE-016",
    "rarity": "RARE",
    "tier": 1,
    "affinity": "Alnathi",
    "sides": {
      "top": 1,
      "right": 4,
      "bottom": 1,
      "left": 6
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#6d3c2f",
      "secondary": "#e0a35a",
      "ink": "#1f120d"
    },
    "series": "core",
    "artUrl": "/cards/core/velvet-thorn-courtesan.png"
  },
  {
    "id": "roc",
    "name": "Roc",
    "collectorNumber": "CORE-017",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Beast",
    "sides": {
      "top": 6,
      "right": 2,
      "bottom": 2,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#4f6277",
      "secondary": "#d7f0f4",
      "ink": "#111923"
    },
    "series": "core",
    "artUrl": "/cards/core/roc.png"
  },
  {
    "id": "forest-troll",
    "name": "Forest Troll",
    "collectorNumber": "CORE-018",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Giant",
    "sides": {
      "top": 5,
      "right": 3,
      "bottom": 3,
      "left": 4
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#3f5d35",
      "secondary": "#b8c779",
      "ink": "#121a0f"
    },
    "series": "core",
    "artUrl": "/cards/core/forest-troll.png"
  },
  {
    "id": "moonwell-diver",
    "name": "Moonwell Diver",
    "collectorNumber": "CORE-019",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Alnathi",
    "sides": {
      "top": 4,
      "right": 1,
      "bottom": 6,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#2e6072",
      "secondary": "#a8e7e1",
      "ink": "#0d1d21"
    },
    "series": "core",
    "artUrl": "/cards/core/moonwell-diver.png"
  },
  {
    "id": "kynathi-highborn",
    "name": "Kynathi Highborn",
    "collectorNumber": "CORE-020",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Kynathi",
    "sides": {
      "top": 3,
      "right": 4,
      "bottom": 5,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#4a3470",
      "secondary": "#d8c3ff",
      "ink": "#170f25"
    },
    "series": "core",
    "artUrl": "/cards/core/kynathi-highborn.png"
  },
  {
    "id": "ghoul",
    "name": "Ghoul",
    "collectorNumber": "CORE-021",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Undead",
    "sides": {
      "top": 5,
      "right": 3,
      "bottom": 2,
      "left": 5
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#405c38",
      "secondary": "#aecf7a",
      "ink": "#121a10"
    },
    "series": "core",
    "artUrl": "/cards/core/ghoul.png"
  },
  {
    "id": "red-imp",
    "name": "Red Imp",
    "collectorNumber": "CORE-022",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Eldritch",
    "sides": {
      "top": 1,
      "right": 5,
      "bottom": 3,
      "left": 5
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#783345",
      "secondary": "#f08061",
      "ink": "#210e13"
    },
    "series": "core",
    "artUrl": "/cards/core/red-imp.png"
  },
  {
    "id": "blue-imp",
    "name": "Blue Imp",
    "collectorNumber": "CORE-023",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Eldritch",
    "sides": {
      "top": 5,
      "right": 2,
      "bottom": 5,
      "left": 2
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#2f4d82",
      "secondary": "#9ec8ff",
      "ink": "#0d1423"
    },
    "series": "core",
    "artUrl": "/cards/core/blue-imp.png"
  },
  {
    "id": "skraal",
    "name": "Skraal",
    "collectorNumber": "CORE-024",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Aberration",
    "sides": {
      "top": 4,
      "right": 4,
      "bottom": 5,
      "left": 2
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#68404f",
      "secondary": "#e2a0a8",
      "ink": "#1c1115"
    },
    "series": "core",
    "artUrl": "/cards/core/skraal.png"
  },
  {
    "id": "laughing-staff-adept",
    "name": "Laughing Staff Adept",
    "collectorNumber": "CORE-024",
    "rarity": "UNCOMMON",
    "tier": 2,
    "affinity": "Reshai",
    "sides": {
      "top": 2,
      "right": 5,
      "bottom": 2,
      "left": 4
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#68404f",
      "secondary": "#e2a0a8",
      "ink": "#1c1115"
    },
    "series": "core",
    "artUrl": "/cards/core/laughing-staff-adept.png"
  },
  {
    "id": "broken-doll",
    "name": "Broken Doll",
    "collectorNumber": "CORE-025",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Construct",
    "sides": {
      "top": 5,
      "right": 2,
      "bottom": 5,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#58616f",
      "secondary": "#d7d0c5",
      "ink": "#171a1f"
    },
    "series": "core",
    "artUrl": "/cards/core/broken-doll.png"
  },
  {
    "id": "myrathi-raider",
    "name": "Myrathi Raider",
    "collectorNumber": "CORE-026",
    "rarity": "COMMON",
    "tier": 2,
    "affinity": "Myrathi",
    "sides": {
      "top": 5,
      "right": 1,
      "bottom": 3,
      "left": 4
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#245f75",
      "secondary": "#7dd3fc",
      "ink": "#0b1b22"
    },
    "series": "core",
    "artUrl": "/cards/core/myrathi-raider.png"
  },
  {
    "id": "ember-page",
    "name": "Ember Page",
    "collectorNumber": "CORE-027",
    "rarity": "UNCOMMON",
    "tier": 2,
    "affinity": "Human",
    "sides": {
      "top": 2,
      "right": 6,
      "bottom": 2,
      "left": 5
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#8a2e27",
      "secondary": "#f0b05e",
      "ink": "#25100d"
    },
    "series": "core",
    "artUrl": "/cards/core/ember-page.png"
  },
  {
    "id": "myrathi-tidecaller",
    "name": "Myrathi Tidecaller",
    "collectorNumber": "CORE-028",
    "rarity": "UNCOMMON",
    "tier": 3,
    "affinity": "Myrathi",
    "sides": {
      "top": 3,
      "right": 6,
      "bottom": 5,
      "left": 4
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#1e6677",
      "secondary": "#93e4e7",
      "ink": "#0a1e23"
    },
    "series": "core",
    "artUrl": "/cards/core/myrathi-tidecaller.png"
  },
  {
    "id": "canopy-duelist",
    "name": "Canopy Duelist",
    "collectorNumber": "CORE-028",
    "rarity": "UNCOMMON",
    "tier": 3,
    "affinity": "Reshai",
    "sides": {
      "top": 3,
      "right": 4,
      "bottom": 4,
      "left": 6
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#1e6677",
      "secondary": "#93e4e7",
      "ink": "#0a1e23"
    },
    "series": "core",
    "artUrl": "/cards/core/canopy-duelist.png"
  },
  {
    "id": "siguapa",
    "name": "Siguapa",
    "collectorNumber": "CORE-029",
    "rarity": "UNCOMMON",
    "tier": 3,
    "affinity": "Eldritch",
    "sides": {
      "top": 5,
      "right": 5,
      "bottom": 3,
      "left": 5
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#32244d",
      "secondary": "#c39cff",
      "ink": "#100b19"
    },
    "series": "core",
    "artUrl": "/cards/core/siguapa.png"
  },
  {
    "id": "flesh-amalgamation",
    "name": "Flesh Amalgamation",
    "collectorNumber": "CORE-030",
    "rarity": "RARE",
    "tier": 3,
    "affinity": "Aberration",
    "sides": {
      "top": 6,
      "right": 3,
      "bottom": 6,
      "left": 5
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#6e3544",
      "secondary": "#e78c9a",
      "ink": "#200f14"
    },
    "series": "core",
    "artUrl": "/cards/core/flesh-amalgamation.png"
  },
  {
    "id": "king-garath",
    "name": "King Garath",
    "collectorNumber": "CORE-031",
    "rarity": "EPIC",
    "tier": 4,
    "affinity": "Human",
    "sides": {
      "top": 7,
      "right": 5,
      "bottom": 4,
      "left": 6
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#6c4a25",
      "secondary": "#e0bd69",
      "ink": "#211608"
    },
    "series": "core",
    "artUrl": "/cards/core/king-garath.png"
  },
  {
    "id": "snallygaster",
    "name": "Snallygaster",
    "collectorNumber": "CORE-032",
    "rarity": "UNCOMMON",
    "tier": 4,
    "affinity": "Eldritch",
    "sides": {
      "top": 4,
      "right": 6,
      "bottom": 6,
      "left": 3
    },
    "lore": "Nothing here...",
    "palette": {
      "primary": "#33435f",
      "secondary": "#a8c6ff",
      "ink": "#101622"
    },
    "series": "core",
    "artUrl": "/cards/core/snallygaster.png"
  }
];
