import { copyFile, mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "yaml";
import { assertUniqueCardIds, parseCardSetFile } from "../src/game/content-schema";
import type { CardTemplate } from "../src/game/types";

const ROOT = process.cwd();
const CARDS_DIR = path.join(ROOT, "content/cards");
const PUBLIC_CARDS_DIR = path.join(ROOT, "public/cards");
const OUT_FILE = path.join(ROOT, "src/game/content.generated.ts");
const ART_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp", ".svg"] as const;

async function main() {
  const entries = await readdir(CARDS_DIR, { withFileTypes: true });
  const yamlFiles = entries
    .filter((entry) => entry.isFile() && /\.(ya?ml)$/i.test(entry.name))
    .map((entry) => entry.name)
    .sort();

  if (yamlFiles.length === 0) {
    throw new Error(`No YAML card files found in ${path.relative(ROOT, CARDS_DIR)}.`);
  }

  const cardSets = await Promise.all(
    yamlFiles.map(async (filename) => {
      const absolutePath = path.join(CARDS_DIR, filename);
      const raw = await readFile(absolutePath, "utf8");
      return parseCardSetFile(parse(raw), filename);
    })
  );

  assertUniqueCardIds(cardSets);
  await copyCardArt(cardSets.map((set) => set.series));

  const cards: CardTemplate[] = await Promise.all(
    cardSets.flatMap((set) =>
      set.cards.map(async (card) => ({
        ...card,
        series: card.series ?? set.series,
        rarity: card.rarity as CardTemplate["rarity"],
        tier: card.tier as CardTemplate["tier"],
        affinity: card.affinity as CardTemplate["affinity"],
        artUrl: await resolveArtUrl(card.id, card.series ?? set.series, card.artUrl)
      }))
    )
  );

  const output = [
    "/* This file is generated by scripts/generate-content.ts. Edit content/cards/*.yaml instead. */",
    'import type { CardTemplate } from "./types";',
    "",
    `export const CARD_TEMPLATES: CardTemplate[] = ${JSON.stringify(cards, null, 2)};`,
    ""
  ].join("\n");

  await mkdir(path.dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, output, "utf8");
  console.log(`Generated ${path.relative(ROOT, OUT_FILE)} from ${yamlFiles.length} card set file(s).`);
}

async function copyCardArt(seriesIds: string[]) {
  for (const series of new Set(seriesIds)) {
    const sourceDir = path.join(CARDS_DIR, series);
    const entries = await readdir(sourceDir, { withFileTypes: true }).catch(() => []);
    const imageFiles = entries.filter(
      (entry) =>
        entry.isFile() &&
        ART_EXTENSIONS.includes(
          path.extname(entry.name).toLowerCase() as (typeof ART_EXTENSIONS)[number]
        )
    );

    if (imageFiles.length === 0) continue;

    const destinationDir = path.join(PUBLIC_CARDS_DIR, series);
    await mkdir(destinationDir, { recursive: true });

    await Promise.all(
      imageFiles.map((entry) =>
        copyFile(path.join(sourceDir, entry.name), path.join(destinationDir, entry.name))
      )
    );
  }
}

async function resolveArtUrl(cardId: string, series: string, artUrl?: string) {
  if (artUrl?.startsWith("/cards/")) {
    return artUrl;
  }

  if (artUrl) {
    const fileName = path.basename(artUrl);
    return `/cards/${series}/${fileName}`;
  }

  for (const extension of ART_EXTENSIONS) {
    const fileName = `${cardId}${extension}`;
    const sourcePath = path.join(CARDS_DIR, series, fileName);
    try {
      await readFile(sourcePath);
      return `/cards/${series}/${fileName}`;
    } catch {
      // Try the next supported image extension.
    }
  }

  return undefined;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
