import { copyFile, mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { parse } from "yaml";
import sharp from "sharp";
import { assertUniqueCardIds, parseCardSetFile } from "../src/game/content-schema";
import type { CardRarity, CardTemplate } from "../src/game/types";

const ROOT = process.cwd();
const CARDS_DIR = path.join(ROOT, "content/cards");
const BORDERS_DIR = path.join(ROOT, "content/borders");
const PUBLIC_CARDS_DIR = path.join(ROOT, "public/cards");
const OUT_FILE = path.join(ROOT, "src/game/content.generated.ts");
const ART_EXTENSIONS = [".jpg", ".jpeg", ".png", ".webp", ".svg"] as const;

async function main() {
  const entries = await readdir(CARDS_DIR, { withFileTypes: true });
  const yamlFiles = entries
    .filter((entry) => entry.isFile() && /\.(ya?ml)$/i.test(entry.name))
    .map((entry) => entry.name)
    .sort();

  if (yamlFiles.length === 0) {
    throw new Error(`No YAML card files found in ${path.relative(ROOT, CARDS_DIR)}.`);
  }

  const cardSets = await Promise.all(
    yamlFiles.map(async (filename) => {
      const absolutePath = path.join(CARDS_DIR, filename);
      const raw = await readFile(absolutePath, "utf8");
      return parseCardSetFile(parse(raw), filename);
    })
  );

  assertUniqueCardIds(cardSets);

  const cards: CardTemplate[] = await Promise.all(
    cardSets.flatMap((set) =>
      set.cards.map(async (card) => ({
        ...card,
        series: card.series ?? set.series,
        rarity: card.rarity as CardTemplate["rarity"],
        tier: card.tier as CardTemplate["tier"],
        affinity: card.affinity as CardTemplate["affinity"],
        artUrl: await resolveArtUrl(card.id, card.series ?? set.series, card.artUrl)
      }))
    )
  );

  await buildCardArt(cards);

  const output = [
    "/* This file is generated by scripts/generate-content.ts. Edit content/cards/*.yaml instead. */",
    'import type { CardTemplate } from "./types";',
    "",
    `export const CARD_TEMPLATES: CardTemplate[] = ${JSON.stringify(cards, null, 2)};`,
    ""
  ].join("\n");

  await mkdir(path.dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, output, "utf8");
  console.log(`Generated ${path.relative(ROOT, OUT_FILE)} from ${yamlFiles.length} card set file(s).`);
}

/**
 * Resolves the rarity-border overlay for each rarity, by convention
 * `content/borders/<RARITY>.png`. Rarities without a border (e.g. one still
 * being drawn) are simply absent and fall back to copying the raw art.
 */
async function loadRarityBorders(): Promise<Partial<Record<CardRarity, string>>> {
  const rarities: CardRarity[] = ["COMMON", "UNCOMMON", "RARE", "EPIC", "LEGENDARY"];
  const borders: Partial<Record<CardRarity, string>> = {};
  for (const rarity of rarities) {
    const borderPath = path.join(BORDERS_DIR, `${rarity}.png`);
    try {
      await stat(borderPath);
      borders[rarity] = borderPath;
    } catch {
      // No border for this rarity yet; cards keep their raw art.
    }
  }
  return borders;
}

/**
 * Writes each card's display art to `public/cards/<series>/`. When a border
 * exists for the card's rarity, the (borderless) art is composited under the
 * transparent rarity overlay; otherwise the art is copied verbatim. The output
 * path matches what the old copy step produced, so nothing downstream changes.
 */
async function buildCardArt(cards: CardTemplate[]) {
  const borders = await loadRarityBorders();
  const missingBorders = new Set<CardRarity>();

  await Promise.all(
    cards.map(async (card) => {
      if (!card.artUrl?.startsWith("/cards/")) return;

      const relative = card.artUrl.slice("/cards/".length);
      const source = path.join(CARDS_DIR, relative);
      const destination = path.join(PUBLIC_CARDS_DIR, relative);
      await mkdir(path.dirname(destination), { recursive: true });

      const borderPath = card.artUrl.endsWith(".png") ? borders[card.rarity] : undefined;

      if (borderPath) {
        await sharp(source)
          .composite([{ input: borderPath }])
          .png()
          .toFile(destination);
      } else {
        if (card.artUrl.endsWith(".png")) missingBorders.add(card.rarity);
        await copyFile(source, destination);
      }
    })
  );

  if (missingBorders.size > 0) {
    console.warn(
      `No rarity border for ${[...missingBorders].join(", ")}; those cards use raw art. ` +
        `Add content/borders/<RARITY>.png to enable.`
    );
  }
}

async function resolveArtUrl(cardId: string, series: string, artUrl?: string) {
  if (artUrl?.startsWith("/cards/")) {
    return artUrl;
  }

  if (artUrl) {
    const fileName = path.basename(artUrl);
    return `/cards/${series}/${fileName}`;
  }

  for (const extension of ART_EXTENSIONS) {
    const fileName = `${cardId}${extension}`;
    const sourcePath = path.join(CARDS_DIR, series, fileName);
    try {
      await readFile(sourcePath);
      return `/cards/${series}/${fileName}`;
    } catch {
      // Try the next supported image extension.
    }
  }

  return undefined;
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
